### ISSUE TITLE
Docs site not loading?

### ISSUE THREAD

**Issue by AminoffZ** [Ni55aN/d3-node-editor#603]
The [docs](https://rete.js.org/) site is not loading:

```
GET https://unpkg.com/vue@2.6.10/dist/vue.runtime.min.js net::ERR_ABORTED 520
(index):5          GET https://unpkg.com/vue-router@3.0.2/dist/vue-router.min.js net::ERR_ABORTED 520
iview.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (iview.min.js:1:9524)
    at n (iview.min.js:1:400)
    at Object.<anonymous> (iview.min.js:14:23553)
    at n (iview.min.js:1:400)
    at Object.<anonymous> (iview.min.js:39:298157)
    at n (iview.min.js:1:400)
    at Object.<anonymous> (iview.min.js:39:298044)
    at n (iview.min.js:1:400)
    at Object.<anonymous> (iview.min.js:39:291275)
    at n (iview.min.js:1:400)
(anonymous) @ iview.min.js:1
n @ iview.min.js:1
(anonymous) @ iview.min.js:14
n @ iview.min.js:1
(anonymous) @ iview.min.js:39
n @ iview.min.js:1
(anonymous) @ iview.min.js:39
n @ iview.min.js:1
(anonymous) @ iview.min.js:39
n @ iview.min.js:1
(anonymous) @ iview.min.js:1
(anonymous) @ iview.min.js:1
(anonymous) @ iview.min.js:1
(anonymous) @ iview.min.js:1
app.d45ea26e.js:1 Uncaught ReferenceError: Vue is not defined
    at 8bbf (app.d45ea26e.js:1:89708)
    at s (app.d45ea26e.js:1:1708)
    at 56d7 (app.d45ea26e.js:1:21050)
    at s (app.d45ea26e.js:1:1708)
    at 0 (app.d45ea26e.js:1:5551)
    at s (app.d45ea26e.js:1:1708)
    at n (app.d45ea26e.js:1:388)
    at app.d45ea26e.js:1:5516
    at app.d45ea26e.js:1:5521
```

**Comment by AminoffZ** [comment]
Seems to be working now again.
