### ISSUE TITLE
Group inserting error on the console

### ISSUE THREAD

**Issue by ALPEEN** [Ni55aN/d3-node-editor#86]
The following logs appear in the console each time a Group is beeing added in the editor, but the Group features work well.
`alight.js?4f45:6 $scan, error in expression: node.style Cannot read property 'style' of undefined 
Object
 TypeError: Cannot read property 'style' of undefined
    at Object.eval [as exp] (eval at e.expression (webpack-internal:///./node_modules/alight/alight.js), <anonymous>:3:28)
    at m (webpack-internal:///./node_modules/alight/alight.js:6:9650)
    at a.digest (webpack-internal:///./node_modules/alight/alight.js:6:10612)
    at r.bind (webpack-internal:///./node_modules/alight/alight.js:6:26193)
    at Function.r.bind (webpack-internal:///./node_modules/alight/alight.js:6:26742)
    at Object.eval (webpack-internal:///./node_modules/alight/alight.js:7:19122)
    at m (webpack-internal:///./node_modules/alight/alight.js:6:10094)
    at a.digest (webpack-internal:///./node_modules/alight/alight.js:6:10612)
    at a.scan (webpack-internal:///./node_modules/alight/alight.js:6:11294)
    at EditorView.update (webpack-internal:///./node_modules/d3-node-editor/build/d3-node-editor.js:3690:22)`

**Comment by Ni55aN** [comment]
dcac7c6092172ff8acf2357038503d561aa7572b
